# Generated by Django 2.0.4 on 2018-04-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20180429_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='hotel_name',
            new_name='hotel',
        ),
    ]
